baseURL = "https://yacine.engineering/"
languageCode = "fr-fr"
defaultContentLanguage = "fr"
title = 'Yacine Salhi'
theme = "anubis2"

colorTheme = "auto"
colorThemeSwitcher = true

social = [
    { id = "docs", url = "https://gohugo.io/documentation/" },
    { id = "github", url = "https://github.com/Rehodotexe" },
    { id = "linkedin", url = "#" },
    { id = "email", url = "#" },
    { id = "facebook", url = "#" },
    { id = "instagram", url = "#" },
    { id = "netease-music", url = "#" },
    { id = "telegram", url = "#" },
    { id = "x", url = "https://x.com/__reho" },
    { id = "youtube", url = "#" }
]

[[menu.main]]
identifier = "home"
name = "Accueil"
url = "/"
weight = 1

[[menu.main]]
identifier = "about"
name = "À propos"
url = "/about/"
weight = 2

[[menu.main]]
name = "Articles"
identifier = "archive"
url = "/posts/"
weight = 3

[[menu.main]]
identifier = "Étiquettes"
name = "Étiquettes"
url = "/tags/"
weight = 4